# Generated by Django 3.2.7 on 2026-06-05 07:44

from django.db import migrations, models

def update_existing_config(apps, schema_editor):
    SiteConfig = apps.get_model('home', 'SiteConfig')
    config, created = SiteConfig.objects.get_or_create(pk=1)
    config.hero_heading = "AI-Powered IT Solutions"
    config.hero_highlight = "Built to Transform Your Business"
    config.hero_subheading = "We help businesses automate, digitize, and grow with smart technology services."
    config.save()

def reverse_update_existing_config(apps, schema_editor):
    SiteConfig = apps.get_model('home', 'SiteConfig')
    try:
        config = SiteConfig.objects.get(pk=1)
        config.hero_heading = "Your Mission, Our"
        config.hero_highlight = "Technology"
        config.hero_subheading = "From Mission to Reality With AI-Driven IT Services"
        config.save()
    except SiteConfig.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herovideo_image_herovideo_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='company_name',
            field=models.CharField(default='Anthem Global', help_text='Company name shown in the top navbar logo.', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_heading',
            field=models.CharField(default='AI-Powered IT Solutions', help_text='First part of the large hero headline.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_highlight',
            field=models.CharField(default='Built to Transform Your Business', help_text='The gradient-coloured word in the hero headline.', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subheading',
            field=models.TextField(default='We help businesses automate, digitize, and grow with smart technology services.', help_text='Descriptive line below the main headline.'),
        ),
        migrations.RunPython(update_existing_config, reverse_update_existing_config),
    ]
